### ISSUE TITLE
Utilizar Spring Rest para camada de Recursos

### ISSUE THREAD

**Issue by otaviocx** [felansu/Qr-BiblioKode-Ws#2]
A arquitetura proposta baseia-se em recursos Web, advento promovido pelos Serviços Web RESTful. Com o framework Spring Rest e seguindo a especificação JAX-RS, é possível implementar todos os princípios da arquitetura RESTful. Esta atividade destina-se à configuração para utilização de tal framework no arquitetura do software backend.

**Comment by aparpires** [comment]
Nossa, que bom que está progredindo ! Depois preciso analisar esse código
para entender...

Não está viajando? Pensei que estivesse...

não respondi ao email do diagrama de classe porque achei que deveria
entendê-lo primeiro.

Tenho algumas dúvidas e estou tentando refazer para entender.

Passei a tarde toda com visita e por isso ainda não terminei o que comecei.

2015-02-28 16:56 GMT-03:00 Ferran Gonzalez Alonso <notifications@github.com>
:

> Closed #2 <https://github.com/felansu/Qr-BiblioKode-Ws/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felansu/Qr-BiblioKode-Ws/issues/2#event-243811967>.
>



-- 


Aparecida Pires
